# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(310, 450)  # Kích thước tối thiểu
        MainWindow.setMaximumSize(310, 450)  # Thêm kích thước tối đa = tối thiểu (không cho phóng to)
        MainWindow.resize(310, 450)
        
        # Lưu reference để tính toán responsive
        self.MainWindow = MainWindow
        
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 290, 410))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 290, 410))
        self.label.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #b2ebf2, stop:1 #e0f7fa);\n"
"border-radius: 15px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.btnLogin = QtWidgets.QPushButton(parent=self.widget)
        self.btnLogin.setGeometry(QtCore.QRect(20, 310, 250, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnLogin.setFont(font)
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLogin.setStyleSheet("QPushButton#btnLogin{\n"
"    background-color: #4A90E2;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton#btnLogin:hover {\n"
"    background-color: #357ABD;\n"
"}\n"
"QPushButton#btnLogin:pressed {\n"
"    padding-right: 5px;\n"
"    padding-bottom:5px;\n"
"    background-color: #2C5F9E;       /* Khi nhấn giữ */\n"
"}\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.widget)
        self.txtPassword.setGeometry(QtCore.QRect(20, 250, 250, 30))
        self.txtPassword.setStyleSheet("color: #2F4F4F;  /* Slate gray hiện đại */\n"
"font-size: 14px;\n"
"border-radius:5px;\n"
"\n"
"")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.txtUsername = QtWidgets.QLineEdit(parent=self.widget)
        self.txtUsername.setGeometry(QtCore.QRect(20, 210, 250, 30))
        self.txtUsername.setStyleSheet("color: #2F4F4F;  /* Slate gray hiện đại */\n"
" font-size: 14px;\n"
"border-radius:5px;\n"
"\n"
"")
        self.txtUsername.setObjectName("txtUsername")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 170, 150))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(70)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgba(0, 0, 0, 180)")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.creatAccount = QtWidgets.QLabel(parent=self.widget)
        self.creatAccount.setGeometry(QtCore.QRect(20, 360, 240, 20))
        self.creatAccount.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.creatAccount.setStyleSheet("color: rgba(0, 0, 0, 180)")
        self.creatAccount.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.creatAccount.setObjectName("creatAccount")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Thêm event handler cho responsive
        MainWindow.resizeEvent = self.on_resize

    def on_resize(self, event):
        """Xử lý responsive khi thay đổi kích thước cửa sổ"""
        window_width = self.MainWindow.width()
        window_height = self.MainWindow.height()
        
        # Tính toán vị trí widget ở giữa
        widget_width = 290
        widget_height = 410
        
        # Căn giữa widget
        x = (window_width - widget_width) // 2
        y = (window_height - widget_height) // 2
        
        # Đảm bảo không ra ngoài biên
        x = max(10, x)
        y = max(10, y)
        
        # Cập nhật vị trí widget
        self.widget.setGeometry(QtCore.QRect(x, y, widget_width, widget_height))
        self.label.setGeometry(QtCore.QRect(0, 0, widget_width, widget_height))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnLogin.setText(_translate("MainWindow", "L o g I n"))
        self.txtPassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.txtUsername.setPlaceholderText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", ""))
        self.creatAccount.setText(_translate("MainWindow", "Create an Account?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
