# Form implementation generated from reading ui file 'mainClient.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Login.logout import LogoutHandler

class Ui_MainWindow(object):
    def __init__(self, username, client, main_window):
        self.username = username
        self.client = client
        self.main_window = main_window
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 290, 410))
        self.widget.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #e0f7fa, stop:1 #ffffff);\n"
"border-radius: 15px;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(60, 170, 170, 50))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.btnLogout = QtWidgets.QPushButton(parent=self.widget)
        self.btnLogout.setGeometry(QtCore.QRect(0, 370, 50, 28))
        self.btnLogout.setStyleSheet("QPushButton#btnLogout{\n"
"    background-color: #4A90E2;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"\n"
"\n"
"}\n"
"QPushButton#btnLogout:hover {\n"
"    background-color: #357ABD;\n"
"}\n"
"QPushButton#btnLogout:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top:5px;\n"
"    background-color: #2C5F9E;       /* Khi nhấn giữ */\n"
"}\n"
"")
        self.btnLogout.setObjectName("btnLogout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btnLogout.clicked.connect(self.on_logout_clicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PycTalk"))
        self.btnLogout.setText(_translate("MainWindow", "Logout"))
    
    def on_logout_clicked(self):
        self.logout_handler = LogoutHandler(self.client, self.main_window)
        self.logout_handler.logout(self.username)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
