# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SignInWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 450)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 290, 410))
        self.widget.setObjectName("widget")
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 290, 410))
        self.label_7.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #b2ebf2, stop:1 #e0f7fa);\n"
"border-radius: 15px;\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.btnSignin = QtWidgets.QPushButton(parent=self.widget)
        self.btnSignin.setGeometry(QtCore.QRect(20, 330, 250, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSignin.setFont(font)
        self.btnSignin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSignin.setStyleSheet("QPushButton#btnSignin{\n"
"    background-color: #4A90E2;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton#btnSignin:hover {\n"
"    background-color: #357ABD;\n"
"}\n"
"QPushButton#btnSignin:pressed {\n"
"    padding-right: 5px;\n"
"    padding-bottom:5px;\n"
"    background-color: #2C5F9E;       /* Khi nhấn giữ */\n"
"}\n"
"")
        self.btnSignin.setObjectName("btnSignin")
        self.txtPasswordSignin = QtWidgets.QLineEdit(parent=self.widget)
        self.txtPasswordSignin.setGeometry(QtCore.QRect(20, 230, 250, 30))
        self.txtPasswordSignin.setStyleSheet("color: #2F4F4F;  /* Slate gray hiện đại */\n"
"font-size: 14px;\n"
"border-radius:5px;\n"
"\n"
"")
        self.txtPasswordSignin.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPasswordSignin.setObjectName("txtPasswordSignin")
        self.txtUsernameSignin = QtWidgets.QLineEdit(parent=self.widget)
        self.txtUsernameSignin.setGeometry(QtCore.QRect(20, 190, 250, 30))
        self.txtUsernameSignin.setStyleSheet("color: #2F4F4F;  /* Slate gray hiện đại */\n"
" font-size: 14px;\n"
"border-radius:5px;\n"
"\n"
"")
        self.txtUsernameSignin.setObjectName("txtUsernameSignin")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(60, 20, 170, 150))
        font = QtGui.QFont()
        font.setFamily("dripicons-v2")
        font.setPointSize(70)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgba(0, 0, 0, 180)")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.backToLogin = QtWidgets.QLabel(parent=self.widget)
        self.backToLogin.setGeometry(QtCore.QRect(20, 375, 240, 20))
        self.backToLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.backToLogin.setStyleSheet("color: rgba(0, 0, 0, 180)")
        self.backToLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.backToLogin.setObjectName("backToLogin")
        self.txtEmail = QtWidgets.QLineEdit(parent=self.widget)
        self.txtEmail.setGeometry(QtCore.QRect(20, 270, 250, 30))
        self.txtEmail.setStyleSheet("color: #2F4F4F;  /* Slate gray hiện đại */\n"
" font-size: 14px;\n"
"border-radius:5px;\n"
"\n"
"")
        self.txtEmail.setObjectName("txtEmail")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSignin.setText(_translate("MainWindow", "S i g n  I n "))
        self.txtPasswordSignin.setPlaceholderText(_translate("MainWindow", "Password"))
        self.txtUsernameSignin.setPlaceholderText(_translate("MainWindow", "Username"))
        self.label_8.setText(_translate("MainWindow", ""))
        self.backToLogin.setText(_translate("MainWindow", "Back to Login"))
        self.txtEmail.setPlaceholderText(_translate("MainWindow", "Email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
